modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="dinosaurworld"
version="1.0.0"
displayName="Dinosaur world"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Jurko, MCreator"

[[dependencies.dinosaurworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



